// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjobshrbtpiancjzhukr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb2JzaHJidHBpYW5janpodWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODUzNjUsImV4cCI6MjA3MzY2MTM2NX0.fO8jOrVs12kuNKyTKdF3U7rPedMKZc14opgQmUA_nCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});